apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-psu
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lisandius/lab-cicd.git
    targetRevision: release
    path: server-k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-psu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
